### ISSUE TITLE
게임 엔진 설계 및 검증 ~12/23

### ISSUE THREAD

**Issue by jjm159** [jungle-royale/jungle-royale-game-server#1]

**Comment by joohyuk99** [comment]
https://github.com/jungle-royale/protobuf-test

protobuf - UDP 사용하여 GO - C#간 통신 검증

**Comment by joohyuk99** [comment]
https://github.com/jungle-royale/protobuf-test/commit/619b0137821a1b375104ba1281e1a0416ea27ec0

game init 통신 확인 / 테스트 준비 완
